### ISSUE TITLE
Suggested architecture and possible solutions

### ISSUE THREAD

**Issue by avelarder** [mmato90/Talento#7]
Hey guys,
Please find the suggested solution architecture on the link down below.
[https://1drv.ms/u/s!Aqmm0vmel5qdhOB7Ez20FWHlyo7w6A](https://1drv.ms/u/s!Aqmm0vmel5qdhOB7Ez20FWHlyo7w6A
)
You application should work perfectly, I modified the connection string in order to make it work on my desktop.

Regards.

**Comment by mmato90** [comment]
Already changed the structure of the Solution.
